# Generated by Django 2.2.5 on 2019-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('new_f', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('item_description', models.TextField(default='xyz')),
                ('category', models.TextField(choices=[('APPETIZERS', 'APPETIZERS'), ('VEGETARIAN DOSAS', 'VEGETARIAN DOSAS'), ('NON-VEGETARIAN DOSAS', 'NON-VEGETARIAN DOSAS'), ('VEGETARIAN SPECIALTIES', 'VEGETARIAN SPECIALTIES'), ('NON-VEGETARIAN SPECIALTIES', 'NON-VEGETARIAN SPECIALTIES'), ('SEA FOOD ENTREES', 'SEA FOOD ENTREES'), ('DESSERTS & BEVERAGES', 'DESSERTS & BEVERAGES')])),
            ],
        ),
    ]
