# Generated by Django 2.2.5 on 2019-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_auto_20191114_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(default=''),
        ),
    ]
