# Generated by Django 2.2.5 on 2019-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_auto_20191114_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
    ]
