# Generated by Django 2.2.5 on 2019-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_auto_20191116_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
